### ISSUE TITLE
Share some data between board files for troubleshooting

### ISSUE THREAD

**Issue by base64bits** [inflex/OpenBoardData#17]
Some boards share the same net names and it will be nice to share the troubleshooting steps between them, for example 820-00165 and 820-3437 both could share the same steps to fix the backlight or SMC etc, it will be nice to have a common file for troubleshooting those 2 boards but keep the other info like net names etc separate.

**Comment by inflex** [comment]
I have pondered over this a bit but I think it's something that I won't bother trying to code in any sort of "aliasing" for; as it's really more of a one-time setup and we can cut-paste between the similar boards.

If I go down the path of having shared files it begins to complicate the process and can lead us further in to corner cases that cannot be easily resolved.

**Comment by base64bits** [comment]
Understood, for now I always have open VS Code with all the files of the boards I work on often and make updates to them as I  need to and copy paste between them as need it.
