### ISSUE TITLE
Unable to load OBD in FlexBV

### ISSUE THREAD

**Issue by DeckerCHAN** [inflex/OpenBoardData#19]
![image](https://user-images.githubusercontent.com/1845937/116816232-686ea500-aba4-11eb-9d83-b187a9b296f0.png)
![image](https://user-images.githubusercontent.com/1845937/116816250-7fad9280-aba4-11eb-8b97-cd1623d20987.png)
![image](https://user-images.githubusercontent.com/1845937/116816263-90f69f00-aba4-11eb-8643-6bad3b590c42.png)
![image](https://user-images.githubusercontent.com/1845937/116816327-d61ad100-aba4-11eb-9cb4-cd73d6efafb4.png)
![image](https://user-images.githubusercontent.com/1845937/116816760-994fd980-aba6-11eb-9703-05c399304788.png)

**Comment by inflex** [comment]
R12xx will resolve this as I shift to a server-based pull system.  For the interim it's non-functional.

**Comment by DeckerCHAN** [comment]
Ok cool. Thanks for the reply.
