### ISSUE TITLE
820-00165 BKL_ISET missing value

### ISSUE THREAD

**Issue by renthraysk** [inflex/OpenBoardData#9]
BKL_ISET line is missing a value.

https://github.com/inflex/OpenBoardData/blob/14025a2d1730a3da3188d26f81950360069be627/obdata/laptops/apple/820-00165.txt#L41

**Comment by warnerbryce** [comment]
I'm double checking this. 
I will modify it in consequence.

**Comment by renthraysk** [comment]
Was writing a parser for the data in go, and flagged up this issue. Cheers.
